### ISSUE TITLE
Add option for Align on Layout component

### ISSUE THREAD

**Issue by ghost** [gymnastjs/gymnast#364]
As I was working with this library one of the features that I felt I needed was the ability to vertically align items. Right now the only component I saw that implements `flex-direction: column` is Layout however there is not an option to pass `align` like with the Grid. I was able to get this to work by manually passing a style but I think it would be good to make the Layout and Grid components more consistent.

**Comment by obartra** [comment]
This feature is [already documented](https://gymnast.readme.io/docs/layout#section-api) but missing, adding it as a bug

**Comment by obartra** [comment]
Closing since we'll be removing `Layout` on the next version
