### ISSUE TITLE
minPageWidth not respected by smaller iPhone screens

### ISSUE THREAD

**Issue by jeffwklein** [gymnastjs/gymnast#367]
- iPhone 5 on latest operating system renders screen smaller than 400px in width.
- To make our app fully visible on smaller screens like this, we set the `minPageWidth` property in `ConfigProvider` to 1.
- Using Chrome devtools to simulate these smaller screen sizes, this worked great, and we merged the code.
- However, on a real iPhone device, you still must scroll on the x-axis to view the entire page, so `minPageWidth` is not respected properly.

**Comment by obartra** [comment]
Hey Jeff, thanks for reporting this issue!

- Have you been able to repro this issue on a Saucelabs emulator? (using a manual session is fine)
- Do you know what the culprit is or have a hacky workaround?

Contributions are most welcome. Let me know if you want help getting started. If you are unable to, the answers to these questions will help us automate testing and fix it sooner.

**Comment by jeffwklein** [comment]
I have not tried this on a saucelabs emulator, just the iPhone device itself. Do we have access to these emulators? I have never used one.

Also, now that I double check the chrome devtools, they have removed iPhone 5 as an option for aspect ratio testing. However, the 'responsive' option behaves as expected for really small screen widths.

**Comment by jeffwklein** [comment]
And to the second question I do not know what the culprit is unfortunately.. i think the quickest hacky workaround I can think of off the top of my head would be altering the meta tag to scale the page down a bit. But this is not ideal obviously

**Comment by obartra** [comment]
My guess is that it's [this issue](https://stackoverflow.com/a/38308119/1189684). We could add `min-device-width` and `max-device-width` to the defaults [here](https://github.com/gymnastjs/gymnast/blob/master/src/defaults.js#L6-L21) and make them match the `max-width` and `min-width`.

We'll also need to add `maxDeviceWidth` and `minDeviceWidth` maps [here](https://github.com/gymnastjs/gymnast/blob/master/src/withResolution/withResolution.logic.js#L62-L69).

Do you want to try that fix?

**Comment by jeffwklein** [comment]
further notes:
- iphone 5 and before are 320 pixels in width.
- later iphone screens render at 375px width (at smallest). the minPageWidth property does work for these screens, interestingly, since 400px is the minimum by default, so the property is not being ignored.
