### ISSUE TITLE
Reduce React Trace

### ISSUE THREAD

**Issue by obartra** [gymnastjs/gymnast#370]
Due to core / withResolution and Grid / Col, gymnast pollutes the react component tree considerably.

This ticket is to explore alternatives

**Comment by obartra** [comment]
Unintentionally closed

**Comment by arahansen** [comment]
This has been partially addressed by #376. Given how much `withResolution` does with React lifecycles, I'm not sure it will be feasible to remove it completely from the dev tree.

**Comment by obartra** [comment]
It won't be trivial for sure, but it only registers and unregisters events on mount / unmount. If instead of setting state it returns it as an additional property and allows registering callbacks for when queries change we may be able to move it as well. It would be at the expense of some duplication on each component though but it shouldn't be too bad.

On one hand I think we have bigger fish to fry but it would be nice to have a very flat tree for gymnast. It could be a fun exercise to implement `Grid` as a webcomponent and just wrap it in React

**Comment by obartra** [comment]
Closing as this is nice to have but not needed. We can add it later on if needed
